#!/usr/bin/env bash
# Real Ollama probe for OpenHand.
#
# Run on a developer machine (not in CI). Detects whether an Ollama daemon
# is reachable on localhost:11434, lists available models, runs the shortest
# sensible chat round-trip against the smallest tagged model, and writes a
# report to docs/OLLAMA_REAL_TEST.md.
#
# If no daemon is found, prints platform-specific install instructions and
# exits 0 (so this script is safe to invoke from a `npm run` hook).
#
# Usage:
#   ./scripts/check-ollama.sh           # autodetect + report
#   ./scripts/check-ollama.sh --quiet   # only write the report, no chat probe
#
# Intentionally NOT wired into CI: pulling models is many hundreds of MiB
# and the GitHub-hosted runners can't run a GPU anyway.

set -uo pipefail

OLLAMA_URL="${OLLAMA_BASE_URL:-http://localhost:11434}"
QUIET="${1:-}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT="${REPO_ROOT}/docs/OLLAMA_REAL_TEST.md"

color() { printf "\033[%sm%s\033[0m\n" "$1" "$2"; }
info()  { color "1;36" "$*"; }
ok()    { color "1;32" "$*"; }
warn()  { color "1;33" "$*"; }
fail()  { color "1;31" "$*"; }

print_install_hints() {
  cat <<'EOF'

Ollama not reachable at localhost:11434. Install one of:

  macOS (Homebrew):
      brew install ollama
      ollama serve &
      ollama pull qwen2.5:0.5b   # ~400 MiB, runs on CPU

  Linux (one-liner):
      curl -fsSL https://ollama.com/install.sh | sh
      systemctl --user enable --now ollama
      ollama pull qwen2.5:0.5b

  Docker (no host install):
      docker run -d --name ollama -p 11434:11434 \
        -v ollama:/root/.ollama ollama/ollama
      docker exec -it ollama ollama pull qwen2.5:0.5b

Then re-run:  ./scripts/check-ollama.sh
EOF
}

ensure_curl() {
  if ! command -v curl >/dev/null 2>&1; then
    fail "curl not found — install curl and re-run."
    exit 1
  fi
}

probe_daemon() {
  curl -fsS --max-time 3 "${OLLAMA_URL}/api/tags" 2>/dev/null
}

ensure_curl

info "Probing ${OLLAMA_URL} ..."
TAGS_JSON="$(probe_daemon || true)"
if [ -z "${TAGS_JSON}" ]; then
  warn "No Ollama daemon detected."
  print_install_hints
  exit 0
fi

ok "Ollama is up."

# Best-effort model list parsing without jq.
MODELS="$(printf '%s' "${TAGS_JSON}" \
  | tr ',' '\n' \
  | grep -E '"name"[[:space:]]*:' \
  | sed -E 's/.*"name"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/' \
  | sort -u || true)"

if [ -z "${MODELS}" ]; then
  warn "Daemon is running but no models are pulled."
  echo
  echo "Pull a small one to enable the chat probe:"
  echo "    ollama pull qwen2.5:0.5b"
  echo
  MODELS="(none)"
fi

# Pick the smallest-named model (heuristic: shortest tag tends to be the smallest).
PROBE_MODEL="$(printf '%s\n' "${MODELS}" | grep -v '^(none)$' \
  | awk '{ print length, $0 }' | sort -n | head -n1 | awk '{ print $2 }')"

CHAT_OUTPUT="(skipped — no model available)"
CHAT_LATENCY_MS="0"
CHAT_STATUS="skipped"

if [ -n "${PROBE_MODEL}" ] && [ "${QUIET}" != "--quiet" ]; then
  info "Running shortest chat probe with model: ${PROBE_MODEL}"
  REQ_BODY=$(cat <<EOF
{"model":"${PROBE_MODEL}","stream":false,"messages":[{"role":"user","content":"Reply with exactly the word: pong"}]}
EOF
)
  START_NS="$(date +%s%N 2>/dev/null || python3 -c 'import time;print(int(time.time()*1e9))')"
  RAW="$(curl -fsS --max-time 30 -H 'content-type: application/json' \
    -d "${REQ_BODY}" "${OLLAMA_URL}/api/chat" 2>&1 || echo '__FAILED__')"
  END_NS="$(date +%s%N 2>/dev/null || python3 -c 'import time;print(int(time.time()*1e9))')"

  if printf '%s' "${RAW}" | grep -q '__FAILED__'; then
    CHAT_STATUS="failed"
    CHAT_OUTPUT="$(printf '%s' "${RAW}" | head -c 400)"
    fail "Chat probe failed."
  else
    CHAT_STATUS="ok"
    CHAT_OUTPUT="$(printf '%s' "${RAW}" \
      | sed -E 's/.*"content"[[:space:]]*:[[:space:]]*"([^"]*)".*/\1/' \
      | head -c 200)"
    if [ -z "${CHAT_OUTPUT}" ]; then CHAT_OUTPUT="(empty content)"; fi
    CHAT_LATENCY_MS="$(( (END_NS - START_NS) / 1000000 ))"
    ok "Got reply: ${CHAT_OUTPUT}  (${CHAT_LATENCY_MS} ms)"
  fi
fi

mkdir -p "$(dirname "${REPORT}")"
{
  echo "# Ollama Real-Probe Report"
  echo
  echo "_Generated by \`scripts/check-ollama.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)_"
  echo
  echo "**Endpoint:** \`${OLLAMA_URL}\`"
  echo
  echo "## Models discovered"
  echo
  if [ "${MODELS}" = "(none)" ]; then
    echo "_None — pull one with \`ollama pull qwen2.5:0.5b\`._"
  else
    printf '%s\n' "${MODELS}" | while read -r m; do
      [ -z "$m" ] && continue
      echo "- \`$m\`"
    done
  fi
  echo
  echo "## Chat probe"
  echo
  echo "| Field | Value |"
  echo "|-------|-------|"
  echo "| Status | \`${CHAT_STATUS}\` |"
  echo "| Model | \`${PROBE_MODEL:-n/a}\` |"
  echo "| Latency | ${CHAT_LATENCY_MS} ms |"
  echo "| Reply (first 200 chars) | \`${CHAT_OUTPUT}\` |"
  echo
  echo "## Wiring it into OpenHand"
  echo
  echo '```bash'
  echo "LLM_PROVIDER=ollama \\"
  echo "LLM_MODEL=${PROBE_MODEL:-qwen2.5:0.5b} \\"
  echo "OLLAMA_BASE_URL=${OLLAMA_URL} \\"
  echo "  npx tsx examples/hello-world.ts"
  echo '```'
  echo
  echo "_This file is auto-regenerated; commit it only when the snapshot changes meaningfully._"
} > "${REPORT}"

ok "Wrote ${REPORT}"
