#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# demo-walkthrough.sh — record a real CLI walkthrough into docs/DEMO.md.
#
# What it does:
#   Runs a sequence of `openhand` commands non-interactively and captures
#   stdout into a single Markdown document. The sequence covers the primary
#   user journey:
#
#     1. openhand --version
#     2. openhand init -y           (writes a project-local config)
#     3. openhand status            (provider + sandbox + plugins snapshot)
#     4. openhand plugins list      (always works, even empty)
#     5. openhand audit             (the new v0.8 audit command)
#     6. openhand doctor            (env diagnostics)
#     7. openhand chat              (interactive — we pipe `/help`, then `/exit`)
#
# Why the runs are scripted, not screencast:
#   - Every contributor can reproduce the exact same DEMO.md by re-running
#     this script, so we can diff and keep it honest.
#   - The chat step uses MockProvider via `LLM_PROVIDER=mock` so there is
#     ZERO network traffic and no API key needed.
#
# Usage:
#   bash scripts/demo-walkthrough.sh                # writes docs/DEMO.md
#   bash scripts/demo-walkthrough.sh --dry-run      # prints to stdout only
# -----------------------------------------------------------------------------
set -euo pipefail

cd "$(dirname "$0")/.."

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
fi

OUT_FILE="docs/DEMO.md"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

STAMP="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

# Build a fresh CLI bundle so the demo always runs against current source.
npm run build --workspace=apps/cli >/dev/null 2>&1 || true
CLI="node apps/cli/dist/index.js"

# Ensure each invocation is hermetic — point OPENHAND_HOME at a temp dir.
DEMO_HOME="$(mktemp -d)"
trap 'rm -f "$TMP"; rm -rf "$DEMO_HOME"' EXIT
export OPENHAND_HOME="$DEMO_HOME"
export LLM_PROVIDER=mock

# Run a CLI step, fence its output. We pipe through `sed` to strip the
# colour-banner lines (they're noisy in Markdown) and the boxen frame.
run_step() {
  local title="$1"
  local cmd="$2"
  local stdin_payload="${3:-}"

  echo "## $title"
  echo
  echo "Command:"
  echo
  echo '```bash'
  echo "$cmd"
  echo '```'
  echo
  echo "Output:"
  echo
  echo '```text'
  if [[ -n "$stdin_payload" ]]; then
    # `printf` + `eval` is intentional — we want shell-style word-splitting
    # of `$cmd` so quoted args work, while feeding stdin from $stdin_payload.
    printf '%s\n' "$stdin_payload" | eval "$cmd" 2>&1 \
      | sed -E '/^[[:space:]]*[█╭│╰─]/d' \
      | sed -E '/CLI v[0-9]/d' \
      | sed -E '/secure AI assistant/d' \
      | sed -E '/^[[:space:]]*$/N;/^\n$/D' \
      || echo "[step exited non-zero — captured anyway]"
  else
    eval "$cmd" 2>&1 \
      | sed -E '/^[[:space:]]*[█╭│╰─]/d' \
      | sed -E '/CLI v[0-9]/d' \
      | sed -E '/secure AI assistant/d' \
      | sed -E '/^[[:space:]]*$/N;/^\n$/D' \
      || echo "[step exited non-zero — captured anyway]"
  fi
  echo '```'
  echo
}

{
  echo "# OpenHand — recorded CLI walkthrough"
  echo
  echo "> Auto-generated by \`scripts/demo-walkthrough.sh\` at $STAMP."
  echo "> Re-run the script to regenerate. No API key needed (uses MockProvider)."
  echo "> \`OPENHAND_HOME\` is pointed at a throwaway directory so your"
  echo "> real \`~/.openhand\` is untouched."
  echo

  run_step "1. Version" "$CLI --version"
  run_step "2. Init (default config)" "$CLI init -y"
  run_step "3. Status" "$CLI status"
  run_step "4. Plugins list" "$CLI plugins list"
  run_step "5. Audit (NEW in v0.8)" "$CLI audit"
  run_step "6. Doctor" "$CLI doctor"

  # Chat is interactive — we feed `/help` so the user can see the slash-command
  # surface, then `/exit` so the REPL terminates cleanly. We feed via stdin and
  # rely on `chat`'s line-loop to read each line.
  run_step "7. Chat REPL (slash help, then exit)" "$CLI chat" "$(printf '/help\n/exit\n')"

  echo "## Notes"
  echo
  echo "- Every step above ran end-to-end without hitting the network."
  echo "- \`audit\` is new in v0.8 — it scans every installed plugin's"
  echo "  declared scopes and assigns a risk band based on what each scope"
  echo "  can reach (see \`apps/cli/src/commands/audit.ts\` for the weights)."
  echo "- \`status\` reads the *real* sandbox policy via"
  echo "  \`SecureSandbox.getPolicy()\` — the printed allow-lists are exactly"
  echo "  what the sandbox would enforce on a live task."
  echo "- The MockProvider keeps the chat REPL fully offline. Switch via"
  echo "  \`LLM_PROVIDER=openai\` (or \`anthropic\`, \`ollama\`) for a real"
  echo "  backend — tests/real/ has live smoke coverage for each."
  echo
  echo "## How to regenerate"
  echo
  echo '```bash'
  echo 'bash scripts/demo-walkthrough.sh             # writes docs/DEMO.md'
  echo 'bash scripts/demo-walkthrough.sh --dry-run   # prints to stdout only'
  echo '```'
} > "$TMP"

if [[ "$DRY_RUN" -eq 1 ]]; then
  cat "$TMP"
else
  mv "$TMP" "$OUT_FILE"
  echo "wrote $OUT_FILE"
fi
