#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# generate-demo.sh — regenerate docs/demo-transcript.md from a real run.
#
# What it does:
#   1. Runs `examples/hello-world.ts` with the MockProvider (no API key, no
#      network) so every contributor can reproduce the output byte-for-byte.
#   2. Captures stdout/stderr into a Markdown fence.
#   3. Writes the output to docs/demo-transcript.md with a generated-at stamp.
#
# Why a real run (not a hand-written transcript):
#   - If the example drifts, the transcript drifts. CI can diff the regen
#     output against the committed file to catch silent breakage.
#
# Usage:
#   bash scripts/generate-demo.sh               # prints + writes
#   bash scripts/generate-demo.sh --dry-run     # prints to stdout only
# -----------------------------------------------------------------------------
set -euo pipefail

cd "$(dirname "$0")/.."

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
fi

OUT_FILE="docs/demo-transcript.md"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

STAMP="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

{
  echo "# OpenHand — recorded demo transcript"
  echo
  echo "> Auto-generated by \`scripts/generate-demo.sh\` at $STAMP."
  echo "> Re-run the script to regenerate. No API key needed — uses MockProvider."
  echo
  echo '## 1. Hello world (examples/hello-world.ts)'
  echo
  echo 'Command:'
  echo
  echo '```bash'
  echo 'LLM_PROVIDER=mock npx tsx examples/hello-world.ts'
  echo '```'
  echo
  echo 'Output:'
  echo
  echo '```text'
  LLM_PROVIDER=mock npx tsx examples/hello-world.ts 2>&1 || echo "[hello-world exited non-zero]"
  echo '```'
  echo
  echo '## 2. Agent shell loop (examples/agent-shell-loop.ts)'
  echo
  echo 'Command:'
  echo
  echo '```bash'
  echo 'LLM_PROVIDER=mock npx tsx examples/agent-shell-loop.ts'
  echo '```'
  echo
  echo 'Output:'
  echo
  echo '```text'
  LLM_PROVIDER=mock npx tsx examples/agent-shell-loop.ts 2>&1 || echo "[agent-shell-loop exited non-zero]"
  echo '```'
  echo
  echo '## 3. Shell automation policy check (examples/shell-automation.ts)'
  echo
  echo 'Command:'
  echo
  echo '```bash'
  echo 'npx tsx examples/shell-automation.ts'
  echo '```'
  echo
  echo 'Output:'
  echo
  echo '```text'
  npx tsx examples/shell-automation.ts 2>&1 || echo "[shell-automation exited non-zero]"
  echo '```'
  echo
  echo '## Notes'
  echo
  echo '- All three runs use `MockProvider` or pure-function policy probes, so'
  echo '  there is **zero** network traffic.'
  echo '- `LLM_PROVIDER=openai` / `anthropic` / `ollama` will hit a real backend.'
  echo '- The `agent-shell-loop` demo shells out through the sandbox — only the'
  echo '  default-allowed commands (`ls`, `echo`, `cat`, …) will succeed.'
  echo '- `shell-automation` calls the pure `checkCommand` / `checkPath`'
  echo '  helpers, so it is deterministic and safe to run in CI.'
  echo
  echo '## How to regenerate'
  echo
  echo '```bash'
  echo 'bash scripts/generate-demo.sh            # writes docs/demo-transcript.md'
  echo 'bash scripts/generate-demo.sh --dry-run  # just prints to stdout'
  echo '```'
} > "$TMP"

if [[ "$DRY_RUN" -eq 1 ]]; then
  cat "$TMP"
else
  mv "$TMP" "$OUT_FILE"
  echo "wrote $OUT_FILE"
fi
